### ISSUE TITLE
Tweet not rendered properly??

### ISSUE THREAD

**Issue by lem0n4id** [rebelchris/astro-static-tweet#2]
I stumbled upon this repo and found it to be pretty cool. However, I'm not sure if the tweet is supposed to look like this or not.

This is a screenshot from the [demo website](https://astro-static-tweet.netlify.app/) 👇 
![image](https://user-images.githubusercontent.com/61219881/154736945-4ba8cc3e-7995-40ad-89f8-f721de62ea2b.png)

**Comment by rebelchris** [comment]
Hi @lem0n4id Thanks for noticing this.
I actually updated the package and demo site to reflect Astro 0.22+ and have it working on the 0.23 branch now. (With styling 💖)
